project:
  type: website
  output-dir: docs
website:
  title: "Extensions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - boostVSbag.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

